"""empty message

Revision ID: 04a5e96bc184
Revises: be404d5bb7f1
Create Date: 2020-01-05 18:34:42.012832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a5e96bc184'
down_revision = 'be404d5bb7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'token_expiration')
    # ### end Alembic commands ###
