"""empty message

Revision ID: 32267f65023f
Revises: d5e5161bce43
Create Date: 2020-01-05 14:14:36.530551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32267f65023f'
down_revision = 'd5e5161bce43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'author_id')
    # ### end Alembic commands ###
