"""empty message

Revision ID: d5e5161bce43
Revises: 3a7da7cbd134
Create Date: 2020-01-05 13:33:17.400603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e5161bce43'
down_revision = '3a7da7cbd134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_issue_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('issuer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['issuer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_issue_history_issue_date'), 'book_issue_history', ['issue_date'], unique=False)
    op.create_index(op.f('ix_book_issue_history_return_date'), 'book_issue_history', ['return_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_issue_history_return_date'), table_name='book_issue_history')
    op.drop_index(op.f('ix_book_issue_history_issue_date'), table_name='book_issue_history')
    op.drop_table('book_issue_history')
    # ### end Alembic commands ###
